<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CitizensFinancialGroup.Threvw.Policies.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Elements.ApplicationModel.Abstractions\Elements.ApplicationModel.Abstractions.csproj" />
    <ProjectReference Include="..\..\Elements.Core\Elements.Core.csproj" />
    <ProjectReference Include="..\..\Elements.Data.Abstractions\Elements.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\Elements.Validation.Abstractions\Elements.Validation.Abstractions.csproj" />
    <ProjectReference Include="..\..\Elements.Validation.FluentValidation\Elements.Validation.FluentValidation.csproj" />
  </ItemGroup>

</Project>
