<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CitizensFinancialGroup.Threvw.Tenants.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDb.Driver" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Elements.Data.MongoDb\Elements.Data.MongoDb.csproj" />
    <ProjectReference Include="..\Tenant.Service.Domain\Tenant.Domain.csproj" />
  </ItemGroup>

</Project>
