<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CitizensFinancialGroup.Threvw.Policies.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDb.Driver" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\elements\Elements.Data.Abstractions\Elements.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\elements\Elements.Data.MongoDb\Elements.Data.MongoDb.csproj" />
    <ProjectReference Include="..\Policy.Service.Domain\Policy.Domain.csproj" />
  </ItemGroup>

</Project>
