<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CitizensFinancialGroup.Elements.ApplicationModel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elements.Core\Elements.Core.csproj" />
    <ProjectReference Include="..\Elements.Validation.Abstractions\Elements.Validation.Abstractions.csproj" />
  </ItemGroup>

</Project>
